name: 'MS Teams Notification'
description: 'Send adaptive card notification to MS Teams webhook'
author: 'DU University Relations'

inputs:
  webhook-url:
    description: 'MS Teams webhook URL'
    required: true
  title:
    description: 'Notification title'
    required: false
    default: '❌ Playwright Tests Failed'
  github-repository:
    description: 'GitHub repository (usually ${{ github.repository }})'
    required: true
  github-ref-name:
    description: 'GitHub branch/ref name (usually ${{ github.ref_name }})'
    required: true
  github-sha:
    description: 'GitHub commit SHA (usually ${{ github.sha }})'
    required: true
  github-actor:
    description: 'GitHub actor who triggered the workflow (usually ${{ github.actor }})'
    required: true
  github-workflow:
    description: 'GitHub workflow name (usually ${{ github.workflow }})'
    required: true
  github-server-url:
    description: 'GitHub server URL (usually ${{ github.server_url }})'
    required: true
  github-run-id:
    description: 'GitHub run ID (usually ${{ github.run_id }})'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send MS Teams notification
      shell: bash
      run: |
        # Create JSON payload using jq for proper escaping
        PAYLOAD=$(jq -n \
          --arg title "${{ inputs.title }}" \
          --arg repo "${{ inputs.github-repository }}" \
          --arg branch "${{ inputs.github-ref-name }}" \
          --arg sha "${{ inputs.github-sha }}" \
          --arg actor "${{ inputs.github-actor }}" \
          --arg workflow "${{ inputs.github-workflow }}" \
          --arg url "${{ inputs.github-server-url }}/${{ inputs.github-repository }}/actions/runs/${{ inputs.github-run-id }}" \
          '{
            "type": "message",
            "attachments": [{
              "contentType": "application/vnd.microsoft.card.adaptive",
              "content": {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.4",
                "body": [
                  {
                    "type": "TextBlock",
                    "text": $title,
                    "weight": "Bolder",
                    "size": "Large",
                    "color": "Attention"
                  },
                  {
                    "type": "FactSet",
                    "facts": [
                      {
                        "title": "Repository:",
                        "value": $repo
                      },
                      {
                        "title": "Branch:",
                        "value": $branch
                      },
                      {
                        "title": "Commit:",
                        "value": $sha
                      },
                      {
                        "title": "Triggered by:",
                        "value": $actor
                      },
                      {
                        "title": "Workflow:",
                        "value": $workflow
                      }
                    ]
                  }
                ],
                "actions": [
                  {
                    "type": "Action.OpenUrl",
                    "title": "View Failed Run",
                    "url": $url
                  }
                ]
              }
            }]
          }')
        
        # Send notification with error handling
        HTTP_CODE=$(curl --fail --silent --show-error --write-out "%{http_code}" --output /dev/null \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ inputs.webhook-url }}")
        
        if [ "$HTTP_CODE" -ne 200 ]; then
          echo "Failed to send MS Teams notification (HTTP $HTTP_CODE)"
          exit 1
        fi
        
        echo "MS Teams notification sent successfully"
